### ISSUE TITLE
Remove either solc-select or svm-rs

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#142]
Apparently, on some platforms, ethers expects svm-rs for our work. This leads us to having two tools to manage Solidity. Ideally, we'd have one.

[It appears to be used whenever SOLC_VERSION isn't set.]https://github.com/gakonst/ethers-rs/blob/feaa473ffbabee82e1a20eb58f8bce9fd995dd16/ethers-solc/src/compile/mod.rs#L126-L161) Please note I'm unsure why some systems have this set (like mine must) and why some don't.

**Comment by TheArchitect108** [comment]
svm-rs shows installing solc as a dependency so they do not do the same thing. We can opt to have the user set/update the environment variable, but using both solc select and svm seems to be the better UX.

**Comment by kayabaNerve** [comment]
We should be able to set env variables in our build script. That removes svm-rs and avoids further UX complications.

**Comment by kayabaNerve** [comment]
#331 may supersede this.

**Comment by kayabaNerve** [comment]
Resolved in https://github.com/serai-dex/serai/commit/7d0d1dc382f5634bc34999bce431f7f49f63c3ed.
