### ISSUE TITLE
IBC Support

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#148]
As part of integrating Tendermint, we may be able to expose an IBC compliant interface.

Right now, we produce commits of `Sign(round end, hash)`. Per https://github.com/cosmos/ibc/tree/main/spec/client/ics-007-tendermint-client, it'd need to be signing:

```go
  height: uint64
  timestamp: uint64
  commitmentRoot: []byte
  validatorHash: []byte
  signatures: []Signature
```

And we'd additionally need to define a DB for IBC commitments (used here).

The immediate downside I see is the `signatures` field needing to be secp256k1/Ed25519 full signatures AFAICT. Because of that, we may not want to be IBC Tendermint compliant, yet instead write a light client under their WASM proposal. We'd just have to ensure we can work under a light client.

**Comment by jackzampolin** [comment]
Strangelove may be interested in supporting this work. Here are some tools we have for this:
- https://github.com/strangelove-ventures/ibctest
- https://github.com/cosmos/relayer

**Comment by kayabaNerve** [comment]
Thanks for the info :) The first tool definitely seems extremely useful.

I think this *may* bifurcate into two discussions.

1) sc_tendermint, our Tendermint library, having an IBC flavor
2) Serai supporting IBC

While we do have discussions regarding signatures, #96 #99, I'm not sure it's beneficial to actually implement them. That is greatly beneficial for Serai supporting IBC, as the cosmos-sdk doesn't support BLS nor half-aggregation right now (though I did originally learn of half-aggregation thanks to a cosmos issue), BUT Serai would still have to downgrade from Ristretto to Ed25519. I would rather not pull that trigger.

But for sc_tendermint having an IBC flavor specifically... that doesn't seem too difficult. A modified header serialization (for the commit signatures) and a new DB for the commitmentRoot (for IBC messages) and... Then it would just need a relayer and testing.

**Comment by kayabaNerve** [comment]
Per the same ideology in #88, I believe this is best left to solely the discussion on an IBC flavor for our Tendermint library. Serai itself supporting IBC doesn't immediately seem like a discussion.

**Comment by kayabaNerve** [comment]
There's three different targets for IBC:

1) SRI itself
2) sriBTC, sriETH, sriDAI, sriXMR
3) IBC coins coming onto Serai to be swapped for SRI

The second is the trickiest one to talk on. The economics aren't there. We can't require stake to secure coins, then have absolutely no derived value from securing those coins. When the coins are on our chain, being used in our DEX, causing our own swap fees, the economics are there. When another DEX handles that role, there's no yield back to us. This is the whole dsriXYZ discussion, where exported coins would need to decay a non-trivial amount in order to ensure value on Serai's side (#292).

For SRI itself, that'd enable SRI to be used as coins in the Cosmos ecosystem are, and would simplify swaps from the Cosmos ecosystem to SRI (establishing an IBC channel with Penumbra such that SRI can be swapped over there). We would forfeit that market (Penumbra would earn the fees on SRI swaps, not us), but it'd make it not our bother. The option is to integrate Penumbra as we currently integrate blockchains for the specific swap use-case (though that's inconclusive to other use cases).

For the third option, there's the whole economic security debate being raised, and the question of should we bother? Why try to host our own liquidity pools for 100 coins in the Cosmos ecosystem, when we can host one liquidity pool for 1 coin that has liquidity pools against the other 100 coins?

Regardless, the technical commentary now that Serai uses GRANDPA for finalizations (when this issue was written, it used our bespoke Tendermint implementation) is:
1) We'd need GRANDPA IBC
2) We'd need to extend GRANDPA commits with Tendermint compatible commits
3) We could use our existing cosigning protocol to produce Tendermint commits

That last option is likely the simplest as it's completely on our end and has a minimal amount of code associated. The one note is that technically, the external network validator sets would be the ones doing the Tendermint commit, NOT the Serai blockchain validators. That should be fine, as the external network validator sets are expected to have far more in stake and do run Serai full nodes, yet it raises the question of if Serai validators should also do a DKG/participate in cosigning. It also has weird trust assumptions as it's 67% of 67% (44.89%), not 67%. That still should be more stake than the Serai network itself is meant to handle, and to attempt to split the cosigning validators's Tendermint commits would require 67% of the Serai validator set.

I solely wanted to note the updated commentary.

**Comment by kayabaNerve** [comment]
We don't guarantee production of a cosign within a session (epoch). That would be something requiring adjustment if we wanted to produce commits per IBC standards.

Our security is fine as we track the blockchain with a full node, and if the leading validator set cosigns a block, then that leading validator set legitimately follows an entire on-chain history of validator selection and handovers we've verified. The Serai validators (where cosigning is a protection against malicious/equivocating Serai validators) cannot produce an alternate chain installing its own malicious validators (enabling them to produce their own cosigns) without actually staking as expected to replace the honest validators.
