### ISSUE TITLE
Tendermint sets the genesis time to the nearest 5s interval

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#155]
Tendermint should use a hardcoded value (any non-local testnet) or, in the case of the local Docker network, accept a CLI argument for the time (so Docker can pick a time value, passing it as needed to each node).

**Comment by vrx00** [comment]
https://github.com/serai-dex/serai/pull/160

**Comment by kayabaNerve** [comment]
Fixed via #160 and further commits to the #145.
