### ISSUE TITLE
Slashing and Penalties

### ISSUE THREAD

**Issue by TheArchitect108** [serai-dex/serai#164]
Issue to consolidate discussion regarding validator slashing and other network penalties for bad behavior. Spawned from: https://github.com/serai-dex/serai/pull/145/files#r1026920591 

Majority of discussion here will likely come as a part of the testnet milestone.

**Comment by kayabaNerve** [comment]
> To be a bit more elaborate on slashing, there's two ways to do so.
>
> - If verifiable, use inherent transactions under consensus.
> - If observable, collect votes.
> 
> The latter is far more inefficient, yet also more comprehensive. We slash if a validator fails to propose. We can't create a permanent, cryptographic proof of them being malicious there. Accordingly, we need the latter. Since we need the latter,, it can be the only option we do. Then all events which could be under the former can just be under the latter for now.

From #146.

**Comment by kayabaNerve** [comment]
Closing as a legacy issue compared to #349 and #294.
