### ISSUE TITLE
Litecoin (LTC) integration considerations

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#175]
This is solely a tracking issue for notes on the potential of integrating Litecoin.

Litecoin is a top 20 coin which recently added privacy via MWEB. Since it also adopted Taproot, it should be relatively simple to port the Bitcoin integration. I'd prefer to integrate with MWEB, yet there are a few caveats worth noting to this idea:

1) MWEB has a minimal amount of volume. Currently, it has just under 400k USD.
2) Multiple exchanges have barred MWEB transactions.
3) MWEB is minimally supported. I believe only the official wallet does.

I can't say I care about # 2 given who we are. I'd also hope we could be a driving force of adoption regarding # 1.  The main issue is the integration cost of # 3, potentially being as costly as our Monero integration. While the BTC side of things would be handled (so the overall transaction formats and so on), we'd have to write the MWEB cryptography and implement FROST over it. That'd be both a very interesting contribution to their ecosystem and a mountain of effort which may be completely unsupported.

**Comment by monerobull** [comment]
Listing LTC sounds like it would be relatively easy to do and brings a lot of liquidity, 
Implementing MWEB sounds like it would be the opposite of that. IMOP should be very low priority as long as the MWEB ecosystem itself is so tiny.

**Comment by kayabaNerve** [comment]
Deprecating this issue from lack of use over the past two years/having Discord channels for this topic.
