### ISSUE TITLE
Firo (FIRO) integration considerations

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#177]
This is solely a tracking issue for notes on the potential of integrating Firo.

Firo is outside the top 500 coins, yet has put forth a strong privacy protocol (Lelantus Spark) which will exceed Monero's (in theory, once Firo deploys theirs, until Monero evolves to Seraphis...). Accordingly, I'm personally interested from a tech perspective, even though it's hard to justify it practically.

We'd have to implement their privacy protocol in Rust, yet since they're a BTC fork, may be able to fork bitcoin-rs for the transaction side of things. The signature scheme, a modified Chaum-Pedersen proof, is decomposable to Schnorr and I've actually written an implementation (of the theory, not of whatever they're deploying). This is actually of independent interest to Serai as it's a single signature with multiple nonces, which our FROST library supports (yet currently doesn't test for, even though that branch arguably serves as a test).

**Comment by monerobull** [comment]
I wouldn't bother with FIRO for quite some time, even if it is interesting.

**Comment by kayabaNerve** [comment]
It should be noted Spark's modular design means all Serai may have to do is the Chaum-Pedersen proof, types, and RPC code. This assumes a sufficiently competent/flexible Spark light wallet RPC is available.

**Comment by kayabaNerve** [comment]
Deprecating this issue from lack of use over the past two years/having Discord channels for this topic.
