### ISSUE TITLE
Polkadot ecosystem integration considerations

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#178]
This is solely a tracking issue for notes on the potential of integrating the Polkadot ecosystem.

DOT itself currently sits at 11 on Coingecko. The main thing of note is the entire ecosystem accessible via Polkadot, or whatever part of it we integrate with.

Ideally, we would integrate with a DEX serving as an ecosystem aggregator, letting us solely list a single asset to represent the ecosystem. Currently, Statemint is the intended parachain for tokens across the entire ecosystem, and will be implementing a basic DEX. This may be the perfect target, or we may want to wait for a more competent DEX to develop and gain adoption.

**Comment by kayabaNerve** [comment]
Related #88.

**Comment by kayabaNerve** [comment]
We could also integrate with Moonbeam, potentially via our already in the works ETH integration. This would minimize development effort. Moonbeam also has been establishing itself as a cross-chain leader and presumably has DEXs deployed.

**Comment by kayabaNerve** [comment]
If we go through Moonbeam, I believe we can have a Schnorr-based Substrate account with the Moonbeam coin to pay for fees, not needing #287.

**Comment by Steven-Chang** [comment]
Hi. I've been looking into Monero integration with Aleph Zero and as usual, the universe delivers. 

Aleph Zero is working on ZK-SNARKs for private transactions (as well as many other things). I think it makes a lot of sense to integrate Aleph Zero with Serai Dex.

**Comment by kayabaNerve** [comment]
Deprecating this issue from lack of use over the past two years/having Discord channels for this topic.
