### ISSUE TITLE
Cosmos ecosystem integration considerations

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#179]
This is solely a tracking issue for notes on the potential of integrating the Cosmos ecosystem.

ATOM itself currently sits at 24 on Coingecko. The main thing of note is the entire ecosystem accessible via Cosmos, or whatever part of it we integrate with.

Ideally, we would integrate with a DEX serving as an ecosystem aggregator, letting us solely list a single asset to represent the ecosystem. Currently, Osmosis is the leading DEX and likely the best candidate for integration.

Osmosis supports EdDSA over Ed25519 IIRC, so we should be able to form a multisig without issue.

**Comment by monerobull** [comment]
Osmosis would be cool for lower fee trading USDC than on ETH.

**Comment by kayabaNerve** [comment]
To compare to #178, DOT is 11 yet has no ecosystem projects in the top 100. ATOM is 24 yet in ecosystem has:
- Cronos at 32
- Terra Luna Classic at 40
- Osmosis at 76

While I don't care to list Cronos nor Terra Luna Classic, with the right gateway, it handles the burden while opening the doors. I believe Osmosis would handle all of these (and more, of course).

**Comment by kayabaNerve** [comment]
Cosmos has Ed25519 code yet it isn't usable for user-accounts.

See for a (stale?) next step towards that: https://github.com/cosmos/cosmos-sdk/issues/9227

**Comment by Steven-Chang** [comment]
Coming from the cosmos ecosystem, developed on Secret Network, I don't think it's worth integrating anything from Cosmos right now. Trading volume is extremely low and there's a lot of internal grief regarding atom 2.0, forks, gno etc.

**Comment by kayabaNerve** [comment]
Deprecating this issue from lack of use over the past two years/having Discord channels for this topic.
