### ISSUE TITLE
dalek-ff-group should explicitly wrap the Ed25519 prime subgroup, not Ed25519

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#26]
ff/group doesn't really support torsioned curves, so preventing torsion from being an issue would be beneficial. Specifically, following ed25519consensus would be beneficial.

Would drop the is_torsion_free function from the lib.

**Comment by kayabaNerve** [comment]
It turns out group DOES have a CofactorGroup trait. Implementing that would be most proper, yet my immediate priority now is simply wrapping the prime subgroup.

**Comment by jeffro256** [comment]
How to handle points that lie outside the prime subgroup which exist on-chain in Monero?

**Comment by kayabaNerve** [comment]
Via pain and suffering.

https://github.com/serai-dex/serai/issues/25 for the real answer. dfg is only used in a FROST context, and is optional to the Monero crate if you don't use FROST. That said, standard points under this lib are also currently screened for lack of torsion, which leads to enough conflicts to warrant the open issue.
