### ISSUE TITLE
Ethereum L2s

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#288]
Due to Ethereum's significant gas costs, we should additionally support L2s. This issue will focus on EVM-compatible L2s, which should be trivial to integrate. Per #287, our sole additional requirement would be either Flashbots or EIP-4337.

Non-EVM-compatible L2s, such as Starkware, should be discussed individually in distinct issues.

I'm primarily interested in Arbitrum, which has come out as the #1 L2 per https://l2beat.com/scaling/tvl. Optimism would be the second choice, yet even when you exclude the ARB TVL from Arbitrum, Arbitrum is 3x as large.

From a technical diversity standpoint, also adding ZkSync Era, Polygon's zkEVM, Scroll, or Aztec would be solid. ZkSync Era offers account abstraction, removing the need for Flashbots/4337.

**Comment by Cevedale** [comment]
What do you think of Scroll tho?

**Comment by kayabaNerve** [comment]
Scroll was one of the listed options under technical diversity. I have yet to do a deep dive into the various zkEVMs from a security standpoint (upgradeability,  ZK proofs used) nor their functionality (regarding Ethereum equivalence). One of the biggest impacts would be the support for relayer technology (EIP-4337, Flashbots) though (as originally stated in the issue).

**Comment by kayabaNerve** [comment]
Closing for the same reason as #175 #176 #177 #178 #179
