### ISSUE TITLE
Monero V1 txs serialization issues

### ISSUE THREAD

**Issue by Boog900** [serai-dex/serai#304]
V1 miner txs don't have any signatures and (for non-miner V1 txs) signatures should be  `Vec<Vec<(Scalar, Scalar)>>` not `Vec<(Scalar, Scalar)>`. I have fixed this [here](https://github.com/Cuprate/serai/commit/d8b8ce9837eb1372d167d60ed8f758ed5480854f) which I will upstream with the rest of the legacy types just thought I would make this known. 

I have also began scanning the blockchain and, with that fix, all V1 txs/ blocks can be decoded.

**Comment by kayabaNerve** [comment]
ACK per https://github.com/monero-project/monero/blob/5387018adeba1899a1bc3935b759ad9958d7dfe0/src/cryptonote_basic/cryptonote_basic.h#L213. Thanks for catching this :)
