### ISSUE TITLE
Implement Bulletproofs in Rust

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#31]
Doing so would enable removing `-z muldefs` and make our only reliance on C the hash_to_point function.

**Comment by kayabaNerve** [comment]
Technically, we use CLSAG verify and communicate over the FFI via serialization. We already have an experimental CLSAG verify, which I trust without issue to be *at least as strict* *except* it doesn't reject a variety of 0 cases that Monero does. Accordingly, that can be dropped.

That leaves hash_to_point and BP prove. I'll create a new issue for hash_to_point.

**Comment by kayabaNerve** [comment]
`-z muldefs` was removed with #30 and I no longer feel this is as pressing as the Monero code is appropriately minimal. Accordingly, we shouldn't rush to remove the C CLSAG verify and so on.

**Comment by dan-da** [comment]
You probably are aware of, but just in case:
https://crates.io/crates/bulletproofs

**Comment by kayabaNerve** [comment]
I am! The distinction is we specifically need Monero Bulletproofs. While the existing dalek code could be forked to be Monero Bulletproofs, they aren't right now.

Beyond moving from Ristretto to Ed25519, there's going to be a completely different transcript format. I assume, beyond the Monero INV_8/8 preprocessing, the actual math is the same? Yet there may be a few edge cases there.

Thanks for chiming in though :)

**Comment by dan-da** [comment]
there is also this, which supports bulletproofs+ and ed25519.  but maybe not so fast?
https://crates.io/crates/bulletproof-kzen

**Comment by kayabaNerve** [comment]
We can't legally use that (as it's GPL-licensed and the Monero lib is MIT), and again, we explicitly need Monero Bulletproofs.

It also uses "curv" instead of ff/group? Weird.
