### ISSUE TITLE
Monero CI failure

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#351]
https://github.com/serai-dex/serai/actions/runs/5923190999/job/16058367418

https://github.com/serai-dex/serai/blob/34397b31b1a77e9924ba407649768eb79a7b4590/tests/processor/src/lib.rs#L287 returned invalid node.

This can only happen if:

1) The Monero response wasn't UTF-8.
2) It was an error variant (which it shouldn't be since we're getting a block it gave us the hash for).
3) Our parsing code has an error.
4) Our hash code has an error.

Unfortunately, we do not have the granularity to know what the answer is.

**Comment by kayabaNerve** [comment]
https://github.com/serai-dex/serai/actions/runs/6378881560/job/17310298162?pr=388, same spot.

**Comment by kayabaNerve** [comment]
https://github.com/serai-dex/serai/actions/runs/6377392652/job/17305972503 same spot, different error. Since it was `ConnectionError`, I initially thought the node simply hadn't booted before the test ran, but no, prior calls executed.

Maybe it's some issue with long-lived Monero connections? If I run the binary to reserialize the blockchain for long enough, I eventually get similar behavior...

**Comment by Boog900** [comment]
I'm getting a similar issue in Cuprate every now and then I get error requesting a block or transaction, no other RPC request is giving me issues. I don't think it's because of long-lived connections as I was holding the connections for a while without requesting any blocks with no issues but when I start requesting blocks/ txs I start getting issues.

I did a bit of investigating exposed some errors and found that [here](https://github.com/serai-dex/serai/blob/4ee65ed243afb7ed629b04b3c1bbbd53df9b665f/coins/monero/src/rpc/mod.rs#L150) keeps erroring with `expected value at line 1 column 1`

At the moment I have no clue why

**Comment by Boog900** [comment]
well I found my issue:
```
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
guessing this is unrelated to the orignal issue

**Comment by kayabaNerve** [comment]
If it's from `nginx`, yeah, it's unrelated to the CI failures. I wouldn't be surprised if the Monero node has some similar bs causing out own ConnectionError/InvalidNode reports though.

Our RPC code really needs a large rewrite re: error handling...

**Comment by kayabaNerve** [comment]
I moved the processor tests from expecting a local Monero node to be spawned to using a dockertest setup as part of #405.

I've gotten the following list of errors, from a single run of the processor tests, after doing so:

```
[coins/monero/src/rpc/mod.rs:150] (raw, e) = (
    "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>",
    Error("expected value", line: 1, column: 1),
)
thread 'tokio-runtime-worker' panicked at processor/src/networks/monero.rs:637:8:
called `Result::unwrap()` on an `Err` value: InvalidNode
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[coins/monero/src/rpc/mod.rs:502] e = Custom {
    kind: Other,
    error: "invalid header",
}
[coins/monero/src/rpc/mod.rs:150] (raw, e) = (
    "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>",
    Error("expected value", line: 1, column: 1),
)
[coins/monero/src/rpc/mod.rs:150] (raw, e) = (
    "<html><head><title>Unauthorized Access</title></head><body><h1>401 Unauthorized</h1></body></html>",
    Error("expected value", line: 1, column: 1),
)
thread 'tokio-runtime-worker' panicked at processor/src/networks/monero.rs:637:8:
called `Result::unwrap()` on an `Err` value: InvalidNode
[coins/monero/src/rpc/http.rs:60] e = reqwest::Error {
    kind: Request,
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Ipv4(
                0.0.0.0,
            ),
        ),
        port: Some(
            33512,
        ),
        path: "/",
        query: None,
        fragment: None,
    },
    source: hyper::Error(
        IncompleteMessage,
    ),
}
 ```

I'm guessing this is stumbling into some mess predicated on Monero thinking we're a remote client, not a local one, and treating us with more hostility accordingly? I'll push my branch as-is, though it may be a distinct issue.

**Comment by kayabaNerve** [comment]
Upon more review, the above looks to likely be an issue with our impl of authenticated RPCs.

I am concerned by the InvalidHeader though...

**Comment by kayabaNerve** [comment]
I couldn't finish a run with authentication. Removing it, it seems to be fine. That's.... not good.

**Comment by kayabaNerve** [comment]
Presumably fixed by https://github.com/serai-dex/serai/commit/30691384759c809040c7a39ab9d90a3446276bd1
