### ISSUE TITLE
Should we use rustfmt?

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#39]
https://github.com/serai-dex/serai/compare/develop...rustfmt shows how different it looks. While I believe it's largely fine, it's just that. Fine. I don't believe it notably increased code readability, yet it did settle any potential arguments about style. It has a few notable detriments.

```rs
use std::{io::Read, sync::{Arc, RwLock}};
```

```rs
use std::{
  io::Read,
  sync::{Arc, RwLock},
};
```

I don't know why this was expanded, but it was?

```rs
     let mut commitments = (0 .. self.clsags.len()).map(|c| {
```

```rs
    let mut commitments = (0 .. self.clsags.len())
      .map(|c| {
```

Forcing an extra ident.

```rs
    let outputs = self.rpc
      .get_block_transactions_possible(height).await.unwrap()
      .swap_remove(0).scan(self.empty_view_pair(), false).ignore_timelock();
```
This block took the rpc, got the outputs for a height, and then scanned the coinbase, ignoring the timelock to get the outputs.

```rs
    let outputs = self
      .rpc
      .get_block_transactions_possible(height)
      .await
      .unwrap()
      .swap_remove(0)
      .scan(self.empty_view_pair(), false)
      .ignore_timelock();
```
This is how it was reformatted. While I get why it was, as it's an auto-formatter... is this beneficial?

```rs
        Arc::new(RwLock::new(Some(
          ClsagDetails::new(
            ClsagInput::new(
              Commitment::new(randomness, AMOUNT),
              Decoys {
                i: RING_INDEX,
                offsets: (1 ..= RING_LEN).into_iter().collect(),
                ring: ring.clone()
              }
```

```rs
        Arc::new(RwLock::new(Some(ClsagDetails::new(
          ClsagInput::new(
            Commitment::new(randomness, AMOUNT),
            Decoys {
              i: RING_INDEX,
              offsets: (1 ..= RING_LEN).into_iter().collect(),
              ring: ring.clone(),
            },
```

It also frequently collapses things I wouldn't, though the original was already suboptimal. It was meant to be the wrappers on one line with...

```rs
          e = Some(
            Self::R_nonces(transcript.clone(), generators, self.s[i], ring[i], e.unwrap_or(e_0))
          );
```

```rs
          e = Some(Self::R_nonces(
            transcript.clone(),
            generators,
            self.s[i],
            ring[i],
            e.unwrap_or(e_0),
          ));
```

Or simply changes where it's collapsed.

cc @noot, the person I'm currently fighting on style with :p I'm willing to accept the above `cargo fmt` to resolve this on a project level, yet I do wonder if we shouldn't use an auto formatter yet a style guide/just say be pleasant with the rest of the codebase (like Monero).

**Comment by kayabaNerve** [comment]
Off-GH ack from @noot so looks like it's being merged.

**Comment by noot** [comment]
@kayabaNerve the rustfmt proposed looks good to me!

**Comment by kayabaNerve** [comment]
Closed with https://github.com/serai-dex/serai/pull/46
