### ISSUE TITLE
`Lazy` deref clarity

### ISSUE THREAD

**Issue by hinto-janai** [serai-dex/serai#477]
Is this `(*)` being used here to be clear that a Lazy is being forcefully initialized?

https://github.com/serai-dex/serai/blob/5c047ebe7486254ec549055012c7aa659725e03c/message-queue/src/main.rs#L62

The `.` operator will deref automatically, so `.read()` will work without `(*)`.

**Comment by kayabaNerve** [comment]
If it works without that, I'm fine not having it. The capitalization shows it's some global sufficiently well. Seems like a trivial oversight.

Care to simplify this, or shall I close this issue as-is?
