### ISSUE TITLE
Seed `const`-ness + no alloc

### ISSUE THREAD

**Issue by hinto-janai** [serai-dex/serai#482]
Many operations in the seed generation code (e.g [`/coins/monero/src/wallet/seed/classic.rs`](https://github.com/serai-dex/serai/blob/4de4c186b190e85b306652bda2cbbf47988c1bd6/coins/monero/src/wallet/seed/classic.rs)) can be `const` and need not allocate, e.g:

https://github.com/serai-dex/serai/blob/4de4c186b190e85b306652bda2cbbf47988c1bd6/coins/monero/src/wallet/seed/classic.rs#L40-L45

Could be:
```rust
struct WordList {
  word_list: &'static [&'static str; 1626],
  trimmed_word_list: &'static [&'static str; 1626],
  unique_prefix_length: usize,
}
```

This is uglier and may be harder to maintain.

Although, it does allow `const` operations and after testing, binary search on `1626` elements is at least as fast, if not faster than a hash (and is bounded in time). Some classic seed lists aren't sorted so I'm not sure how that would be solved... although I think all polyseed lists are sorted.

I'm not sure how prevalent this code is - is all of this a waste of time and `Vec/HashMap` are just fine/simpler?

**Comment by kayabaNerve** [comment]
Personally, I don't have opinions on the seed code. It's there for other people, not for Serai. If we can make improvements, great. It's not personally a priority for me nor something I'm too opinionated on (I'm fine leaving opinions to those who will actually use it).

If I was to have a single opinion, it's that minimizing wallet code *as beneficial to hardware wallets* is a goal we should have. This would likely do it, so if a competent PR exists, I'd be happy to merge it :)

**Comment by kayabaNerve** [comment]
I just remembered there is a Rust library for building HashMaps at compile time.

https://crates.io/crates/phf

I'm unsure how this affects your own thoughts, but it may make things more feasible.

**Comment by hinto-janai** [comment]
I assumed adding a dependency would be off limits.

There's also:
```rust
const fn get(word: &str) -> Option<usize> {
    match word {
        "seed_word_0" => Some(0),
        "seed_word_1" => Some(1),
        "seed_word_2" => Some(2),

        /* ... */

        "seed_word_1625" => Some(1625),
        _ => None,
    }
}
```
where you essentially [pray to the LLVM gods](https://github.com/lmammino/mega-match-vs-phf) for your `match` to get optimized into a perfect jump table.

**Comment by kayabaNerve** [comment]
I do frown upon it, especially since when they're not anywhere else in our tree (and phf isn't).

Creating such a match would be feasible since the seed words aren't in our codebase, yet in dedicated files we raw-include.

**Comment by kayabaNerve** [comment]
Closing as won't fix since the seed code has been kicked out to https://github.com/kayabaNerve/monero-wallet-util. I plan to be more liberal over there so feel free to re-open if you're still interested (even with a dependency such as phf).
