### ISSUE TITLE
Document that wallet2 ignores unencrypted payment IDs after hf v12

### ISSUE THREAD

**Issue by j-berman** [serai-dex/serai#512]
https://github.com/monero-project/monero/blob/ac02af92867590ca80b2779a7bbeafa99ff94dcb/src/wallet/wallet2.cpp#L2737-L2750

**Comment by SamsungGalaxyPlayer** [comment]
Additional ref: https://www.getmonero.org/2019/06/04/Long-Payment-ID-Deprecation.html

We decided at the time not to filter them on a consensus level due to implementation complexity concerns, but we removed support from the official wallets.

**Comment by j-berman** [comment]
Looks like a2c3aba82b5217028db718e7361b50e45c8524da removed the comment on this:

> If the payment ID is the unencrypted variant and the block's hf version is v12 or higher [wallet2 would ignore such a payment ID, monero-wallet doesn't]

**Comment by j-berman** [comment]
Whoops, ignore. Just saw this:

https://github.com/serai-dex/serai/blob/a2df54dd6aa4a7519439050b28aa3fc5602ce46c/networks/monero/wallet/src/scan.rs#L344-L353
