### ISSUE TITLE
Define Architecture/Add "Instructions"

### ISSUE THREAD

**Issue by TheArchitect108** [serai-dex/serai#57]
Instructions are DEX commands included within the data fields of each supported currency. Instructions provide the necessary context so that the protocol understands intent and destination.

Define instructions for:

- [ ] Add Bond
- [ ] Withdraw Bond
- [ ] Resign
- [ ] Swap
- [ ] Add Liquidity
- [ ] Withdraw Liquidity
- [ ] Donate

**Comment by kayabaNerve** [comment]
Bond isn't an instruction, it's a Substrate message documented in #53.

Swap/Add are instructions. Withdraw is also a Substrate message, one currently undocumented.

Any donation should be implicit via not providing an instruction.

PR adding a full instruction spec + swap/add shorthand coming momentarily.
