### ISSUE TITLE
monero: monero-wallet only scans txs w/well-formed tx extra, wallet2 can partially parse tx extra and still scan tx

### ISSUE THREAD

**Issue by j-berman** [serai-dex/serai#612]
monero-wallet:

https://github.com/serai-dex/serai/blob/bdcc061bb4bd74fe24dc264899c53822b0e14fe4/networks/monero/wallet/src/scan.rs#L131-L134

https://github.com/serai-dex/serai/blob/bdcc061bb4bd74fe24dc264899c53822b0e14fe4/networks/monero/wallet/src/extra.rs#L304

wallet2 scanner:

https://github.com/monero-project/monero/blob/a1dc85c5373a30f14aaf7dcfdd95f5a7375d3623/src/wallet/wallet2.cpp#L2225-L2231
https://github.com/monero-project/monero/blob/master/src/cryptonote_basic/cryptonote_format_utils.cpp#L562-L568

The `pub_key_and_invalid_padding` test e.g. tested for partial parsing: https://github.com/serai-dex/serai/commit/32c24917c4405023b6b365141f32f4b06b41b32a#diff-e1137a7d8d769c0bca921b874b3303fa6343c7b6190d4011806f103991cdf87eL161-L162

**Comment by kayabaNerve** [comment]
100% my fault and a regression I introduced. Extra has the C++ behavior of returning false on error yet still modifying the arguments (where wallet2 simply ignores the return code) which has caused my confusion. Your first link exemplifies this well.
