### ISSUE TITLE
ink! contracts use nightly

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#66]
As of https://github.com/serai-dex/serai/commit/586aaf1c2b73e5c09dbb849df417c6ee187d0ae5, the contracts use nightly due to OpenBrush. While this is currently on a PR, this bound will be merged.

I really don't appreciate this, not only due to the usage of Rust nightly, yet also due to having default-members + additional for loops after each command. It appears OpenBrush doesn't actually require nightly yet just wants features from nightly. We can either remove it or submit an issue/PR.

**Comment by kayabaNerve** [comment]
It is now worse thanks to the fix included in https://github.com/serai-dex/serai/commit/ead181bdefef76e109f3e57813afbd5a49e58ed0.

**Comment by kayabaNerve** [comment]
Ignoring tests/docs, they only use it for

- `#![feature(min_specialization)]` in `contracts/src/lib.rs`
- `#![feature(drain_filter)]` in `lang/codegen/src/lib.rs`

I don't expect the former to be dropped from OpenBrush, nor do I expect it to be moved to stable anytime soon. We would have to fork/remove OpenBrush to solve this.

**Comment by xgreenx** [comment]
Why didn’t you create an issue in OpenBrush?:) It is not a problem to make it use stable rust if you don’t need to customize the default implementation.

**Comment by kayabaNerve** [comment]
Hey! Thanks for reaching out here.

I didn't because the usage of specialization in traits makes perfect sense lol. It's why I didn't expect it to be dropped from OpenBrush. I didn't want to ask you to feature flag it when it:

1) Makes sense
2) Frequently comes up
3) Is more commentary on the frustrations of monorepos than anything else

Sorry if this seemed negative against OpenBrush. I was pissed off with ink! at the time. OpenBrush itself seems like the best movement forward for ink!, which I appreciate, yet I do believe we're more likely to drop ink! at this time regardless.

**Comment by xgreenx** [comment]
> I didn't because the usage of specialization in traits makes perfect sense lol. It's why I didn't expect it to be dropped from OpenBrush. I didn't want to ask you to feature flag it when it:

We can make it configurable, so it is not a problem to add support for this. BTW, I remember why we didn't worry about it. It because `cargo-contract requires [nightly](https://github.com/paritytech/cargo-contract#cargo-nightly-contract-build) by default=)

> Sorry if this seemed negative against OpenBrush. I was pissed off with ink! at the time. OpenBrush itself seems like the best movement forward for ink!, which I appreciate, yet I do believe we're more likely to drop ink! at this time regardless.

It is sad=( What problem did you face and why did you decide to change your mind? Maybe we can forward issues to ink! team and collaborate on solving.

**Comment by cmichi** [comment]
>Sorry if this seemed negative against OpenBrush. I was pissed off with ink! at the time. OpenBrush itself seems like the best movement forward for ink!, which I appreciate, yet I do believe we're more likely to drop ink! at this time regardless.

Heyhey @kayabaNerve, I'm sorry to hear that. We have an open ear for feedback like this, and it would be helpful for us to understand where you're coming from and how we could have made for a better developer experience for you. Could you share some more info on what you didn't like?

**Comment by kayabaNerve** [comment]
It looks like you mean with ink!, not OpenBrush. I am available via on Matrix (@kayabanerve:matrix.org), being in the OpenBrush channel, or on Discord (Kayaba#5184) where I'm on Polkadot's server if you'd prefer to chat there.

I have frustrations with Parity which carry, such as the complete lack of any place to discuss technology. There used to be a general channel, closed for StackExchange, yet when I was a n00b trying to learn more and I went to StackExchange with my questions, I was criticized for not being focused. How am I supposed to be focused when I don't know what I want to focus on?

Parity's lack of forums and discussion channels is a major barrier to entry. While I wanted to be in the SBP accordingly, hoping to get more support, I was ghosted when I asked about its licensing conditions (I got a response, replied myself, and got nothing). I don't believe that was on purpose, nor malicious, yet I don't care to follow up with y'all for weeks just to try to get more resources.

So regarding ink! itself... it's just way too young. I just wanted to test a contract calling another contract and couldn't, unless I spawned a full node. The issue is there's no documentation on crafting an extrinsic, from Rust, to call a SC on a node. Everything is routed through the web UI, and waterfall, which I wanted to use as reference, uses puppeteer lol. It makes sense for waterfall to use puppeteer if testing the UI is part of its full stack testing, sure, but I just wanted to write tests in Rust without a full browser.

This raises the further question about what do I do when I'm done with testing? Do I just always use JS to call contracts? There's a critical lack of documentation on extrinsics in general, not helped by Parity's re-shuffling of documentation, and then there's not documentation on the contract pallets API specifically. I also just wanted general RPC documentation, and all I saw was the list of JS library calls. There's literally no documentation from Parity, that I could find, establishing it's a JSON RPC 2.0 server and detailing default methods/methods for each pallet.

So I know the testing environment is upcoming, but good news! There's a TypeScript one now! As long as you're willing to add a ton of other requirements to your development environment for it. Also, it doesn't have any docs because its site is down. It took me an hour just to figure out how to install it IIRC (don't you have to install something to install it, and then spawn an environment?)

There's also the comment that the SC-testing node is incompetent for my usage as I need to test chain extensions, which I can't do without forking the SC-testing node, and at that point I should just use my actual node, yet then it needs the custom consensus and... there's just a lot of commentary on why a proper test environment is needed.

So lets say there was a full test environment, and there was full documentation. That would legitimately be fantastic. I despise how the EVM has 32-byte words for everything and wasm is a portable path around that which can theoretically grant much higher efficiency. I just can't test my work right now, nor can I know how to interact with them except via a JS lib I don't plan on using.

OpenBrush's standing in for OpenZeppelin is fine. While I don't appreciate the requirement on nightly due to how impacts monorepos, it makes perfect sense for OB itself, and I'm personally fine re-implementing contracts (as I don't prefer PSP-22 using uint128, personally, and have experience with contracts), but I would miss things like modifiers (justifying a request to OpenBrush for making specification separate from its macros to enable stable-only usage, yet that could also be re-implemented).

**Comment by HCastano** [comment]
Hey @kayabaNerve, thanks for your feedback! We'll get back to you about some of the things you mentioned here, but first I want to get some clarification around two points.

> So I know the testing environment is upcoming, but good news! There's a TypeScript one now! As long as you're willing to add a ton of other requirements to your development environment for it. Also, it doesn't have any docs because its site is down. It took me an hour just to figure out how to install it IIRC (don't you have to install something to install it, and then spawn an environment?)

Which TS environment are you referring to here?

> There's also the comment that the SC-testing node is incompetent for my usage as I need to test chain extensions, which I can't do without forking the SC-testing node, and at that point I should just use my actual node, yet then it needs the custom consensus and... there's just a lot of commentary on why a proper test environment is needed.

I'm assuming you're referring to the [`substrate-contracts-node`](https://github.com/paritytech/substrate-contracts-node) here. It is meant to be used as a starting point for you to work on, so having to fork it in order to add your own chain extensions is the right workflow.

Can you also clarify what you mean about the custom consensus?

**Comment by kayabaNerve** [comment]
[Redspot](https://github.com/patractlabs/redspot). Sarcasm aside, it seemed like a quality tool analoguing well with truffle/hardhat, which I'm used to and respect. It just unfortunately isn't a proper replacement, nor does it have its own proper documentation. I truly don't mean to offend its developer who saw a problem and worked on fixing it just because it's not fixed enough in my opinion, when I believe it's another party's responsibility in the first place. I more wanted to comment on how ink!'s lack of native support for multi-SC testing forced the community to alternatives by parties who couldn't be as comprehensive as Parity can be.

... and then yes, my legitimate complaint with redspot is the installation process :p It's also not pleasant due to the dependencies, yet that's a personal organization/preference perspective. It does what it's supposed to do.

I was referring to that node, and did appreciate aspects of it. The issue is there's different level of tests.
- Unit
- Muilti-contract
- Substrate (where substrate-contracts-node make sense)
- E2E (where the actual node makes sense)

ink!, as of now, only offers unit. While yes, there is a contracts node, there's a lack of existing work on testing against it. It was only posted how to call a contract from Rust on StackExchange a couple weeks ago using subxt. waterfall, the e2e test, runs through the JS interface (part of the stack it's testing, of course). There is an issue open to offer an e2e test macro, running against substrate-contracts-node, yet then my *personal* frustration is I don't want to have to fork and maintain multiple different Substrate nodes for my needs. I'd much rather solely do Unit/Multi-contract/E2E, yet I don't feel comfortable building a full E2E stack before I can even do multi-contract validation. While I can with the test node, I'd need to rebuild a framework and so on :/

Regarding custom consensus, if I wanted the advantage of substrate-contracts-node in my project (per-tx block production, which is a great feature and I do respect substrate-contracts-node as a tool), while maintaining the rest of my node and having two separate nodes in my project, I'd need to feature flag in an alternative consensus. It's just another hassle to participate in the ecosystem.

I truly don't want to attack anyone for the work they've done on this ecosystem. I appreciate the development and the responsiveness. I mean to criticize the presentation of the ecosystem, its timeline, and the fact it's not already in a better position given Parity's backing, the time it has, and how its presented. While recently, I know efforts have ramped up, and more developers are coming on, audits are being scheduled... and that's great! Truly reconsidering ink! now.

I just have my own workflow, which has identified holes in the ecosystem as my workflow would be best with XYZ yet... and was frustrated accordingly. I know I could've made issues on ink!, yet I didn't care to come into a place where y'all were working and be a dick. I had accepted the status, didn't believe it was feasible, and laid out my complaints (with snark, sure). Since this discussion is happening though, which I appreciate, I'm more than happy to further elaborate properly, and I appreciate your time :)

**Comment by kayabaNerve** [comment]
Closing per #180.
