### ISSUE TITLE
solc version

### ISSUE THREAD

**Issue by kayabaNerve** [serai-dex/serai#93]
Brought up due to #91.

When I last reviewed Solidity versions, 0.8.9 was stable. The versions after it introduced bugs, and their fixes, yet hadn't existed for long enough to be considered as bug-free themselves. 0.8.16 has important bugfixes though, and not just for functionality introduced post 0.8.9 (encodeCall and so on).

While I'm fine adopting it, since we're not planning on releasing before it will have been suitably tested anyways, I wanted to raise the discussion and point out pros/cons.

cc @noot 

If 0.8.16 is decided on, which would be my vote, the CI has to be updated as well.

**Comment by noot** [comment]
@kayabaNerve yep, I don't see any reason not to update to the latest version.
